/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ShortLinkDto } from '../model/models';
import { StatsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/{shortCode}
     * @param shortCode 
     */
    _delete(shortCode: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/shorten
     * @param shortLinkDto 
     */
    create(shortLinkDto: ShortLinkDto, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint get /api/stats/{shortCode}
     * @param shortCode 
     */
    getStats(shortCode: string, extraHttpRequestParams?: any): Observable<StatsDto>;

    /**
     * 
     * 
     * @endpoint get /{shortCode}
     * @param shortCode 
     */
    resolveShortCode(shortCode: string, extraHttpRequestParams?: any): Observable<{}>;

}
