nameOverride: ""
fullnameOverride: ""

image:
  repository: shortly
  tag: "latest"
  pullPolicy: IfNotPresent
  # imagePullSecrets: [ ] # e.g., [{ name: regcred }]

imagePullSecrets: [ ]

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: shortly.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources: { }
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 500m
#    memory: 512Mi

env:
  # Additional environment variables for the app
  # - name: SOME_VAR
  #   value: some-value
  [ ]

redis:
  enabled: true
  image: redis:8.4-alpine
  port: 6379
  resources: { }
  persistence:
    enabled: false
    size: 1Gi

monitoring:
  # Add Prometheus annotations to the Service for basic scraping
  annotationsScrape: true

  serviceMonitor:
    enabled: true
    # Namespace where kube-prometheus-stack is installed
    namespace: monitoring
    # Labels for the ServiceMonitor so kube-prometheus-stack picks it up
    additionalLabels:
      release: kube-prometheus-stack
    interval: 15s
    scrapeTimeout: 10s

podAnnotations: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }
