stages:
  - build
  - test
  - quality
  - deploy

variables:
  ECO_CI_SEND_DATA: "false"
  ECO_CI_CO2_GRID_INTENSITY_API_TOKEN: "HIfF0HcByBuFyyLHmGlO"
  ECO_CI_CO2_CALCULATION_METHOD: "location-based"
  ECO_CI_JSON_OUTPUT: "true"

include:
  - local: shortly_java/.gitlab-ci.yml
  - local: shortly_angular/.gitlab-ci.yml
  - remote: 'https://raw.githubusercontent.com/green-coding-solutions/eco-ci-energy-estimation/main/eco-ci-gitlab.yml'

