stages:
  - build
  - test
  - quality
  - deploy

variables:
  ECO_CI_SEND_DATA: "false"
  ECO_CI_CO2_GRID_INTENSITY_API_TOKEN: "HIfF0HcByBuFyyLHmGlO"
  ECO_CI_CO2_CALCULATION_METHOD: "location-based"
  ECO_CI_JSON_OUTPUT: "true"

default:
  tags:
    - docker
  interruptible: true

.rules:shortly_java:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - shortly-java/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - shortly-java/**/*
      when: on_success

.rules:shortly_java_deploy:
  rules:
    - if: '$CI_COMMIT_TAG'
      changes:
        - shortly-java/**/*
      when: on_success

.rules:shortly_frontend:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - shortly-frontend/**/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - shortly-frontend/**/*
      when: on_success

.rules:shortly_frontend_deploy:
  rules:
    - if: '$CI_COMMIT_TAG'
      changes:
        - shortly-frontend/**/*
      when: on_success

include:
  - local: shortly-java/.gitlab-ci.yml
  - local: shortly-frontend/.gitlab-ci.yml
  - remote: 'https://raw.githubusercontent.com/green-coding-solutions/eco-ci-energy-estimation/main/eco-ci-gitlab.yml'

