apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortly.fullname" . }}
  labels:
    {{- include "shortly.labels" . | nindent 4 }}
  {{- if .Values.monitoring.annotationsScrape }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ .Values.service.port }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "shortly.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
