{{- if and .Values.monitoring.serviceMonitor.enabled .Values.monitoring.annotationsScrape }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shortly.fullname" . }}
  labels:
    {{- include "shortly.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace | default .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "shortly.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      path: /actuator/prometheus
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}
