# deploy/argocd/values-docker-desktop.yaml
# Überschreibt NUR die Unterschiede zu values.yaml für Docker Desktop

frontend:
  image:
    pullPolicy: Always
  imagePullSecrets:
    - name: gitlab-registry2

backend:
  image:
    pullPolicy: Always
  imagePullSecrets:
    - name: gitlab-registry2

ingress:
  enabled: true

redis:
  image:
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: neusta-registry
  persistence:
    enabled: false
