# deploy/argocd/values-docker-desktop.yaml
# Überschreibt values.yaml für Docker Desktop mit GitLab Registry

image:
  repository: projectregistry.neusta.de/limmoor/shortly
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

service:
  type: NodePort
  nodePort: 30080

ingress:
  enabled: false

redis:
  enabled: true
  image: docker-repository.intern.neusta.de/redis:8-alpine
  persistence:
    enabled: false

monitoring:
  annotationsScrape: true
  serviceMonitor:
    enabled: true

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
